dist: trusty
language: node_js
node_js:
  - "8"

deploy:
  script:
    - npm install
    - npm run build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
